#!/usr/bin/env bash
# Pre-commit hook template with bypass detection
# Generated by pre-commit but enhanced with enforcement
#
# INSTALLATION:
#   This file should be placed at .git/hooks/pre-commit
#   It will be automatically created/updated by: pre-commit install
#   Manual enhancement: Add bypass detection at the top
#
# CUSTOMIZATION:
#   To enable bypass detection, ensure this hook sources enforce-no-bypass.sh
#   before running the standard pre-commit logic.
#
# MAINTENANCE:
#   - pre-commit install will overwrite this file
#   - You may need to re-add bypass detection after updating pre-commit
#   - Consider using a post-install script to automate this

# ============================================================================
# BYPASS DETECTION (Custom Enhancement)
# ============================================================================
# This section is NOT part of standard pre-commit hooks.
# It must be manually added or scripted after running 'pre-commit install'.

# Enforce no-bypass policy
# Only check if parent is actually git commit with --no-verify
PARENT_ARGS=$(ps -o args= $PPID 2>/dev/null)
if echo "$PARENT_ARGS" | grep -q 'git.*commit.*\-\-no-verify'; then
    echo ""
    echo "╔═══════════════════════════════════════════════════════════════════════════╗"
    echo "║  ❌ ERROR: --no-verify detected in git commit command                    ║"
    echo "║  This is not allowed per project policy.                                 ║"
    echo "║  Fix linting issues instead of bypassing hooks.                          ║"
    echo "║  See: docs/bypass-enforcement.md for details                             ║"
    echo "╚═══════════════════════════════════════════════════════════════════════════╝"
    echo ""
    exit 1
fi

# ============================================================================
# STANDARD PRE-COMMIT HOOK (Auto-generated section)
# ============================================================================
# This section is managed by 'pre-commit install'
# Do not manually edit below this line

# start templated
INSTALL_PYTHON=/usr/local/bin/python3
ARGS=(hook-impl --config=.pre-commit-config.yaml --hook-type=pre-commit)

# end templated

HERE="$(cd "$(dirname "$0")" && pwd)"
ARGS+=(--hook-dir "$HERE" -- "$@")

if [ -x "$INSTALL_PYTHON" ]; then
    exec "$INSTALL_PYTHON" -mpre_commit "${ARGS[@]}"
elif command -v pre-commit > /dev/null; then
    exec pre-commit "${ARGS[@]}"
else
    echo "pre-commit not found.  Did you forget to activate your virtualenv?" 1>&2
    exit 1
fi
